app:
  tesseract_bin: tesseract
  extractor_bin: extractor
  log_level: info
  # pico.red pico.pink pico.fuchsia pico.purple pico.violet pico.indigo
  # pico.blue pico.cyan pico.jade pico.green pico.lime pico.yellow pico.amber
  # pico.pumpkin pico.orange pico.sand pico.grey pico.zinc pico.slate
  theme: pico
  cache_dir: data
preview:
  max_unknown_file_size: 8388608 # 8 mib
server:
  address: 127.0.0.1
  port: 8080
database:
  path: data/database.db
  max_connections: 2
indexing:
  batch_size: 1000
  max_concurrent_batches: 10
  max_concurrent_indexers: 12
  max_retries: 5
  max_file_size: 134217728 # 128 mib
  index_contents_whitelist:
    - "**/*.{pdf,docx,pptx,xlsx,odp,ods,odt,txt,epub,md,rtf,html,png,jpg,jpeg,tif,tiff,bmp,gif,webp}"
    - "**/*.{PDF,DOCX,PPTX,XLSX,ODP,ODS,ODT,TXT,EPUB,MD,RTF,HTML,PNG,JPG,JPEG,TIF,TIFF,BMP,GIF,WEBP}"
    - "**/README"
